### ISSUE TITLE
All your ZEN's crashing,  don't restart your ZEN servers until WLM is back

### ISSUE THREAD

**Issue by phobos777** [WhenLamboMoon/docker-zen-node#81]
Hi all,  WLM is traveling, and he updated the code for securenodes,  unfortunately the code change has a bug in it where your currently "up and stable" servers will get the new code on restart and crash the ZEN servers when they reboot.  therefore wait until WLM is back and he let's us know when the code if fixed.

in the meantime you'll notice your zen servers going offline.

**Comment by 333miiko** [comment]
Please try the latest image and let me know if this works for you.

**Comment by 333miiko** [comment]
Problem seems to be due to the change here:

https://github.com/ZencashOfficial/nodetracker/commit/428fad25498ff43bfcf892aa32e156058912b530

The patch I pushed today should have allowed you to run the `node setup` to re-configure and run the latest supernodes.

For now I have reverted the latest release so that existing nodes can continue to work if they are accidentally rebooted/upgraded.

**Comment by phobos777** [comment]
@333miiko    hi,  i restarted four node with the "reverted code" and it's coming up with even a different error.   sorry @333miiko   looks like the some problem is still going on

![image](https://user-images.githubusercontent.com/15862598/42772270-f06af9d6-88f7-11e8-8639-c1c3293df986.png)

**Comment by 333miiko** [comment]
*Important note for upgrading*

The securenode tracker uses a new configuration meaning if you upgrade it will break. 

Two options are:

- Re-run the installer again, this will re-generate the new config which is compatible with the latest version (remember to grab the latest version)

- Update the config manually

```
cat << EOF > /mnt/zen/secnode/config.json
{
 "active": "secure",
 "secure": {
  "nodetype": "secure",
  "nodeid": null,
  "servers": [
   "ts2.eu",
   "ts1.eu",
   "ts3.eu",
   "ts4.eu",
   "ts4.na",
   "ts3.na",
   "ts2.na",
   "ts1.na"
  ],
  "stakeaddr": "$stakeaddr",
  "email": "$email",
  "fqdn": "$fqdn",
  "ipv": "4",
  "region": "$region",
  "home": "ts1.$region",
  "category": "none"
 }
}
EOF
```

Remember to replace all the variables starting with $
